#!/bin/bash

set -o errexit

rm -rf build
./gradlew build

remote=root@staging.attestation.app
path=/opt/attestation
active=$(ssh $remote readlink $path/deploy)

if [[ $active = $path/deploy_a ]]; then
    target=$path/deploy_b
else
    target=$path/deploy_a
fi

echo
echo active is $active
echo target is $target
echo

rsync -rpcve ssh --chmod=D755,F644 --delete build/libs/ $remote:$target
ssh $remote sync -f $target
ssh $remote ln -snf $target $path/deploy
ssh $remote sync .
ssh $remote systemctl daemon-reload
ssh $remote systemctl restart attestation

echo
echo active is now $target
