#!/bin/bash

set -o errexit

rm -rf build
./gradlew build

remote=attestation@attestation.app
active=$(ssh $remote readlink deploy)

if [[ $active = deploy_a ]]; then
    target=deploy_b
else
    target=deploy_a
fi

echo
echo active is $active
echo target is $target
echo

rsync -rcve ssh --delete build/libs/ $remote:$target
ssh $remote chmod -R a+rX $target
ssh $remote sync
ssh $remote ln -snf $target deploy
ssh $remote sync .
ssh root@attestation.app systemctl restart attestation

echo
echo active is now $target
