#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

./process-static $fd

remote=root@attestation.app
active=$(ssh $remote readlink /srv/attestation.app)

if [[ $active = /srv/attestation.app_a ]]; then
    target=/srv/attestation.app_b
else
    target=/srv/attestation.app_a
fi

echo active is $active
echo target is $target
echo

ssh $remote "rm -rf $target && cp -a $active $target"
rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate static-tmp/ $remote:$target
ssh $remote "ln -snf $target /srv/attestation.app && sync /srv/attestation.app"

echo "root $target;" > nginx-tmp/root_attestation.app.conf
rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate nginx-tmp/{nginx.conf,mime.types,root_attestation.app.conf,snippets} $remote:/etc/nginx/
rsync -ptcv --chmod=755 --fsync --preallocate {local-backup,remote-backup} $remote:/usr/local/bin/
rsync -ptcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.timer $remote:/etc/systemd/system/remote-backup.timer
rsync -ptcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.service $remote:/etc/systemd/system/remote-backup.service
ssh $remote nginx -s reload

echo
echo active is now $target
