#!/bin/bash -x

set -o errexit

rm -rf build
./gradlew build

remote=attestation@attestation.app
current=$(ssh $remote readlink deploy)

if [[ $current = deploy_a ]]; then
    target=deploy_b
else
    target=deploy_a
fi

rsync -rcve ssh --delete build/libs/ $remote:$target
ssh $remote chmod -R a+rX $target
ssh $remote ln -snf $target deploy
ssh root@attestation.app systemctl restart attestation
