#!/bin/bash

set -o errexit -o nounset -o pipefail

generate() {
    echo $1
    qrencode -s 1 -o $1 $2
    gm identify -format '%w×%h\n' $1
    zopflipng -ym $1 $1
}

generate static/donate-bitcoin.png 'bitcoin:bc1qjf6cc59fyyjvdwpqmdthza8um4ewn2fsys36mv?label=GrapheneOS%20Foundation&message=Donation%20to%20GrapheneOS%20Foundation'
generate static/donate-bitcoin-taproot.png 'bitcoin:bc1p5uclzxueyfadgnzxg2afl9rpj4xaxcjnn4aqxj22h5674893uddqn95vtm?label=GrapheneOS%20Foundation&message=Donation%20to%20GrapheneOS%20Foundation'
generate static/donate-bitcoin-bip47.png 'bitcoin:PM8TJKmhJNQX6UTFagyuBk8UGmwKM6yDovEokpHBscPgP3Ac7WdK5zaQKh5XLSawyxiGYZS2a7HkAoeL6oHg7Ahn1VXX888yRG4PwF1dojouPtW7tEHT'
generate static/donate-monero.png 'monero:85zgRCPkTaoDuBCaUGG3vnfBKnpZL1e42KGUaLqfGVr4hsiJxq4hkHvEpUb3prUwgPVZvX5QtfLbyhD4vs5UoL99MKV9LNP?recipient_name=GrapheneOS&tx_description=Donation%20to%20GrapheneOS'
generate static/donate-zcash-transparent.png 'zcash:t1NGgT3EYQhrCyU6ZCY3pvHMpheG2VXvhHu?label=GrapheneOS%20Foundation&message=Donation%20to%20GrapheneOS%20Foundation'
generate static/donate-ethereum.png 'ethereum:0xC822A62E5Ab443E0001f30cEB9B2336D0524fC61'
generate static/donate-cardano.png 'web+cardano:addr1qyyfnce83undm4l3vfy47trsas3m82c77ak5hl8jukpfzgdtfnucytpnq2t38dj7cnyngs6ne05cdwu9gseevgmt3ggqyrpau5'
generate static/donate-litecoin.png 'litecoin:ltc1qqvdg2hgq77rw6sec5l43gxfc03zjx94pryk900?label=GrapheneOS%20Foundation&message=Donation%20to%20GrapheneOS%20Foundation'
