#!/bin/bash

set -o errexit -o nounset -o pipefail

remote=attestation@attestation.app

timestamp=$(date -u +%Y-%m-%dT%H:%m:%SZ)
ssh $remote "rm -rf local-backup"
ssh $remote "mkdir local-backup"

ssh $remote "mkdir local-backup/$timestamp"
ssh $remote "sqlite3 attestation.db \".backup local-backup/$timestamp/attestation.db\""
ssh $remote "sqlite3 samples.db \".backup local-backup/$timestamp/samples.db\""
ssh $remote "tar -cC local-backup $timestamp | zstd -9 | age -r \$(cat backup-public-key.txt) -o local-backup/$timestamp.tar.zst.age"
rsync -v $remote:./local-backup/$timestamp.tar.zst.age backup/
