#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

if [[ $# -eq 1 ]]; then
    fd=$1
else
    touch lock
    exec {fd}< lock
fi

if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

export PATH="$PWD/node_modules/.bin:$PATH"

rm -rf nginx-tmp
cp -a nginx nginx-tmp

gixy nginx-tmp/nginx.conf

rm -rf static-tmp
cp -a static static-tmp

for file in static-tmp/**/*.@(json|webmanifest); do
    json_verify < "$file" >/dev/null
    json_reformat -m < "$file" | sponge "$file"
done

stylelint static-tmp/**/*.css
find static-tmp -name '*.css' -exec csso {} -o {} \;

eslint static-tmp/**/*.js
find static-tmp -name '*.js' -exec terser --ecma 2021 --module -cmo {} {} \;

replace=""
for file in static-tmp/**/*.css static-tmp/**/*.js; do
    hash=$(sha256sum "$file" | head -c 8)
    sri_hash=sha256-$(openssl dgst -sha256 -binary "$file" | openssl base64 -A)
    dest="$(dirname $file)/$hash.$(basename $file)"

    if [[ $file == *.css ]]; then
        replace+=";s@{{css|/${file#*/}}}@<link rel=\"stylesheet\" href=\"/${dest#*/}\" integrity=\"$sri_hash\"/>@g"
    elif [[ $file == *.js ]]; then
        replace+=";s@{{js|/${file#*/}}}@<script type=\"module\" src=\"/${dest#*/}\" integrity=\"$sri_hash\"></script>@g"
    fi

    mv "$file" "$dest"
    replace+=";s@{{integrity|/${file#*/}}}@${sri_hash}@g"
    replace+=";s@{{path|/${file#*/}}}@/${dest#*/}@g"
done

sed -i "$replace" static-tmp/**/*.html nginx-tmp/nginx.conf nginx-tmp/snippets/preload.conf

xmllint --noout static-tmp/**/*.@(html|svg|xml)
validatornu --Werror --also-check-css --also-check-svg static-tmp/**/*.@(css|html|svg)
find static-tmp -name '*.html' -exec html-minifier --collapse-whitespace \
    --process-scripts "application/ld+json" --collapse-boolean-attributes \
    --remove-attribute-quotes --remove-comments --remove-empty-attributes \
    --remove-redundant-attributes --remove-script-type-attributes \
    --remove-style-link-type-attributes --sort-attributes --sort-class-name {} -o {} \;

find static-tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;

brotli_k() {
    brotli -k "$@"
}
export -f brotli_k

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static-tmp -regex '.+\.\(css\|html\|ico\|js\|json\|svg\|txt\|webmanifest\|xml\)' |
    parallel -q ::: brotli_k zopfli_preserve_time :::: -
