#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

export PATH="$PWD/node_modules/.bin:$PATH"

rm -rf static_tmp
cp -a static static_tmp

for file in static_tmp/**/*.@(json|webmanifest); do
    json_reformat -m < "$file" | sponge "$file"
done

find static_tmp -name '*.css' -exec csso {} -o {} \;
find static_tmp -name '*.js' -exec terser --ecma 2021 --module -cmo {} {} \;

replace=""
for file in static_tmp/**/*.css static_tmp/**/*.js; do
    hash=$(sha256sum "$file" | head -c 8)
    dest="$(dirname $file)/$hash.$(basename $file)"
    mv "$file" "$dest"
    replace+=";s|/${file#*/}|/${dest#*/}|g"
done

cp nginx/nginx.conf nginx.conf.tmp
sed -i "$replace" static_tmp/**/*.html nginx.conf.tmp

find static_tmp -name '*.html' -exec html-minifier --collapse-whitespace \
    --process-scripts "application/ld+json" --collapse-boolean-attributes \
    --remove-attribute-quotes --remove-comments --remove-empty-attributes \
    --remove-redundant-attributes --remove-script-type-attributes \
    --remove-style-link-type-attributes --sort-attributes --sort-class-name {} -o {} \;

find static_tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;

brotli_k() {
    brotli -k "$@"
}
export -f brotli_k

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static_tmp -regex '.+\.\(css\|html\|ico\|js\|json\|svg\|txt\|webmanifest\|xml\)' |
    parallel -q ::: brotli_k zopfli_preserve_time :::: -
