#!/bin/bash

set -o errexit -o nounset -o pipefail

timestamp=$(date -u +%Y-%m-%dT%H:%m:%SZ)
rm -rf remote-backup
mkdir remote-backup

mkdir remote-backup/$timestamp
sqlite3 attestation.db ".backup remote-backup/$timestamp/attestation.db"
sqlite3 samples.db ".backup remote-backup/$timestamp/samples.db"
tar c -C remote-backup $timestamp | zstd -9 | age -r $(cat backup-public-key.txt) -o remote-backup/$timestamp.tar.zst.age
sshpass -f cloud-archive-password.txt rsync -v ./remote-backup/$timestamp.tar.zst.age pca@gateways.storage.gra.cloud.ovh.net:backup/
