name: Build server application

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
      - name: Build with Gradle
        run: ./gradlew build
